name: ctlearn_manager
channels:
    - anaconda
    - conda-forge
dependencies:
    - python=3.12
    - numpy
    - ctapipe
    - gammapy
    - pyirf
    - pip
    - ctaplot
    - h5py 
    - astropy
    - pip:
      - ctadata
      - matplotlib