StereoPredictCTLearnModel:
  DLImageReader:
    allowed_tels: [4, 3]
    force_dl1_lookup: False
    TableQualityQuery:
      quality_criteria:
        - ["enough intensity", "hillas_intensity > 25"]
        #- ["not clipped", "leakage_intensity_width_2 < 0.2"]